config/routes.rb
Rails.application.routes.draw do
  resources 'feeds'

  root 'feeds#new'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  validates :feed_url, :url => "true"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
require 'rss'

class FeedsController < ApplicationController
  def new
    @feed = Feed.new
    @feeds = Feed.all.order("created_at DESC") || []
  end

  def index
    @feeds = Feed.all.order("created_at DESC")
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  def show
   @feed = Feed.find(params[:id])
   @feed_url = @feed.feed_url

   @rss_feed = RSS::Parser.parse(@feed_url, false)

  end

  def create
    @feed = Feed.new(feed_params)
    if @feed.save
      flash[:success] = "Successfully created..."
      redirect_to new_feed_path
    else
      flash[:error] = "Please check the params"
      puts @feed.errors.full_messages
      @feeds = Feed.all.order("created_at DESC") || []
      render 'new'
    end
  end

  def destroy
      @feed = Feed.find(params[:id])
      if @feed.destroy
        flash[:success] = "User deleted."
        #redirect_to feeds_url
        redirect_to new_feed_path
      else
        flash[:error] = "Problem in deleting feed.............."
      end
  end

  def update
      @feed = Feed.find(params[:id])
      if @feed.update_attributes(feed_params)
        flash[:success] = "Successfully updated the feed..."
        redirect_to feeds_url
      else
        flash[:error] = "Error in updating feed"
      end
  end

  private

      def feed_params
            params.require(:feed).permit(:feed_url)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_error_messages.html.erb
<% if @feed.errors.any? %>
  <div id='error_explanation'>
     <div class='alert alert-error'>
       The form contains <%= pluralize(@feed.errors.count, 'error')%>.
     </div>
     <ul>
  <%@feed.errors.full_messages.each do |msg| %>
    <li>* <%= msg %> </li>
  <% end %>
     </ul>
  </div>
<%end%>

app/views/feeds/edit.html.erb
<% provide(:title, "Edit Feed Url") %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@feed) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :feed_url %>
      <%= f.text_field :feed_url %>

      <%= f.submit "Save", class: "btn btn-large btn-primary" %>
    <% end %>

<%= link_to "Home", root_path %>
  </div>
</div>

app/views/feeds/index.html.erb
<% provide(:title, 'All Feeds') %>
<h1>All Feeds</h1>
<%#= will_paginate %>

<ol class="feeds">
    <%#= render @feeds %>
    <% @feeds.each do |f| %>
      <li>
          <%= link_to f.feed_url, feed_path(f) %>
          <%= link_to "Edit", edit_feed_path(f) %>&nbsp;&nbsp;
          <%= link_to "delete", f, method: :delete, data: { confirm: "You sure?" } %>
          <br />
          </li>
    <% end %>
  </ol>
<%#= will_paginate %>

app/views/feeds/new.html.erb
<% provide(:title, "New Rss Feed") %>


<div class='row'>
  <h1>Add Rss Feed Urls</h1>
  <div class='span6 offset3'>

    <%= form_for(:feed, url: feeds_path) do |f| %>
      <%#= f.label :feed_url %>
      <%= f.text_field :feed_url, placeholder: "Feed Url" %>&nbsp;&nbsp;

      <%= f.submit "Add", class: 'btn btn-primary'%>

    <% end %>
    <%#= render :index %>
</div>
</div>

    <br />

<div class='row'>
  <h1>All Feed Urls</h1>
  <div class='span6 offset3'>

<%#= will_paginate %>

<ol class="feeds">
    <%#= render @feeds %>
    <% @feeds.each do |f| %>
      <li>
          <%= link_to f.feed_url, feed_path(f) , {"onmouseover" => "Parse this feed", "onmouseout" => "Read this feed"}%>
          <%= link_to "Edit", edit_feed_path(f) %>&nbsp;&nbsp;
          <%= link_to "delete", f, method: :delete, data: { confirm: "You sure?" } %>
          <br />
          </li>
    <% end %>
  </ol>
  </div>
</div>

app/views/feeds/show.html.erb
<% provide(:title, @feed.feed_url) %>
<div class="row">
  <aside class="span4">
  <section>
  <h3>
      Rss Feed Titles:
  </h3>
  <ol>
    <% @rss_feed.items.each do |feed| %>
          <li>
                <%= link_to feed.title, '#'%>

                <br />

                <%= feed.description.html_safe %>

            </li>
    <% end %>
  </ol>
  <br />
  <br />
  </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
  <%#a href="http://railstutorial.org/">Rails Tutorial</a%>
  by Mallikarjuna
</small>
<nav>
<ul>
  <li><%= link_to "Home", root_url%></li>
  <li><%= link_to "About",   '#' %></li>
  <li><%= link_to "Contact", '#' %></li>
  <%#li><a href="http://news.railstutorial.org/">News</a></li%>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "Rss Parser", root_path, id: "logo" %>
    <nav>
    <ul class="nav nav-tabs navbar-right">
      <li><%= link_to "Add Feed", new_feed_path %></li>
      <li><%= link_to "All Feeds", feeds_path %></li>
      <li><%= link_to "What?", "http://www.problogger.net/what-is-rss/" %></li>
            </nav>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssNew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
</head>
<body>

<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>